# Generated by Django 4.2.14 on 2024-07-23 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=10)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=64)),
                ("email", models.CharField(max_length=120)),
                ("password_hash", models.CharField(max_length=128)),
                ("salt", models.CharField(max_length=128)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Transactions",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "types",
                    models.CharField(
                        choices=[("income", "income"), ("expense", "expense")],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("occu_date", models.DateField()),
                ("notes", models.TextField()),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                (
                    "category_id",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="transactions",
                        to="finance.categories",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="user_transactions",
                        to="finance.users",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="categories",
            name="user_id",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="categories",
                to="finance.users",
            ),
        ),
        migrations.CreateModel(
            name="budgets",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("limits", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                (
                    "category_id",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="budget_category",
                        to="finance.categories",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="budgets",
                        to="finance.users",
                    ),
                ),
            ],
        ),
    ]
