# Generated by Django 4.2.14 on 2024-07-31 08:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transactions",
            old_name="category_id",
            new_name="category",
        ),
    ]
