# Generated by Django 4.2.14 on 2024-08-08 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_rename_category_id_transactions_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="categories",
            name="category_type",
            field=models.CharField(
                choices=[("income", "Income"), ("expense", "Expense")],
                default="Expense",
                max_length=7,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="categories",
            name="user",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
