# Generated by Django 4.2.14 on 2024-08-14 07:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_categories_category_type_alter_categories_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgets',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budgets',
            name='period_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='budgets',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
