# Generated by Django 4.2.14 on 2024-08-20 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_budgets_end_date_budgets_period_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgets',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='budgets',
            name='start_date',
        ),
        migrations.AddField(
            model_name='budgets',
            name='month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgets',
            name='year',
            field=models.PositiveIntegerField(default=2024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budgets',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.categories'),
        ),
        migrations.AlterField(
            model_name='budgets',
            name='period_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10),
        ),
        migrations.AlterField(
            model_name='budgets',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
