name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Migrations
        working-directory: ./backend
        env:
          DATABASE_URL: postgres://default:kxKu1TZna6Mr@ep-dry-snowflake-a4czgkr8-pooler.us-east-1.aws.neon.tech/verceldb
        run: |
          python manage.py makemigrations
          python manage.py migrate

      #- name: Run Custom command
      #  working-directory: ./backend
      #  env:
      #    DATABASE_URL: postgres://default:kxKu1TZna6Mr@ep-dry-snowflake-a4czgkr8-pooler.us-east-1.aws.neon.tech/verceldb
      #  run: |
      #    python manage.py create_default_categories
      #    python manage.py create_demo_data

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: prj_JBsafA95C0WohJRSJemJKku7tvGh
          working-directory: ./backend
          vercel-args: "--prod"
